### ISSUE TITLE
lspconfig roadmap

### ISSUE THREAD

**Issue by mjlbach** [neovim/nvim-lspconfig#1221]
Creating a tracking issue to discuss the "future" of lspconfig so I have something to point users at, as a lot of these questions get asked cyclically.  I'll go back and edit.

### Background
lspconfig as it stands has 5 main functions:
1. A collection of cmd/settings/initialization options that need to be passed to `start_client` in order to launch a language server
2. Watching for new "projects", that is, folders under which all files that match a configured language server should be attached to a given language server
3. It adds a hook to call `workspace/didChangeConfiguration` after initialization (this should probably be in core, and I PR'd it)
4. Attaching buffers to a given project's language server
5. Diagnostic/management helper commands like "LspInfo, LspStart, LspStop"

That's it. All the other functionality is located in core, and we should probably move some of the above there as well.

### Problems

* Although lspconfig has the requisite table to pass to `start_client`, it's currently not possible to just do something like (`lua vim.lsp.start_client(require("lspconfig").servers.pyright.config)`). We should better factor out things that are specific to project management (like our internal root_dir resolver function) from settings/init_options/cmd which can just be directly forwarded to start_client. I think this prevents people from realizing how easy it is to *not* use lspconfig to launch/attach buffers to servers, see [this gist](https://gist.github.com/mjlbach/d5a141c457380802e3444e19503f8572).

*  Lspconfig currently has tension between being "just configs" and something more fully featured. As mentioned in point 1, we don't make it easy for external plugins to transparently use `start_client` specific keys, and many plugins end up completely bypassing the built-in project management aspects of lspconfig because they are primitive

    If we were to remove all but the configs, then the built-in client would be basically unusable for a casual user. They would need to call `start_client` initially with a given project root manually, and then manually attach each new buffer to a given client.

    Alternatively, which I propose, is we lean into the project aspect of lspconfig. The things that are missing are 1. The ability to have project local settings, which would let you customize settings/init_options/root_dir per project (the latter probably implicitly by having something like `.nvim-project.json in the root of your project which is preferrred) and 2. Manual management of projects (you should be able, for example, to call something like `:LspLaunch pyright /path/to/my/project`).

* TJ, Mathias, and I have been talking about plugin specifications for awhile. Lspconfig is supposed to be "on-spec" only, and externalize off-spec behavior to extensions. While nvim-jdtls, flutter-tools.nvim, rust-tools.nvim, nvim-metals all have similar structure, it would be good to provide formal documentation/a template for how to make these plugins such that it's easier for contributors to get started. Ideally, lspconfig is only a "fallback" in favor of more full-featured plugins like these that can be tailored to the intricacies of the language/server.

* Make the entire language server start up process completely async, to avoid any issues with resolving project directories that involve expensive external calls (see rust)

* Add support for remote language server plugins like distant (not explicitly, but expose the correct APIs to make this easy for plugin authors)

    rootUri/workspaceFolders: is sent in start_client as part of `initializationOptions`  This used to be validated in `start_client` prior to 0.5.1/0.6, because certain language servers break (scala) when you do not provide `rootUri`. We will need to validate which servers work without `rootUri`, and also make it clear to users that this will result in impaired functionality of the language server (two bare python files in the same folder, barring any true root, would no longer recognize each other's imports for example). In the case that a given file is *not* a member of a project and a new flag `requires_workspace` is false, these buffers should be attached to a single shared "scratch" language server to avoid launching a new language server per lone file.

### (tentative) plan open to contributor discussion (targeting neovim 0.7)

- [ ] add a project local configuration file (json?) that allows users to customize settings/root_dir/init_options per project
- [ ] add functions for manual project launching/termination/management similar to `LspStart/Stop/Restart`
- [ ] upstream project management/lspinfo (checkhealth?)/lspconfig utilities around path and root detection to core (maybe with plenary.path?). Ideally this would reduce boiler plate shared between nvim-jdtls, nvim-metals, etc.
- [ ] write plugin developer documentation

### Other thoughts

* I need to find a way to get more people to take ownership over the configurations/respond to issues. We have grown beyond the point where a single contributor (me) can test/debug/answer questions for all language ecosystems.

**Comment by justinmk** [comment]
> I need to find a way to get more people to take ownership over the configurations/respond to issues. We have grown beyond the point where a single contributor (me) can test/debug/answer questions for all language ecosystems.

It helps to have some clear signaling. The readme used say prominently that this repo is "best effort" and per-config support requests are not welcome. That was removed in https://github.com/neovim/nvim-lspconfig/pull/910 , maybe we should revisit it

**Comment by mjlbach** [comment]
> It helps to have some clear signaling. The readme used say prominently that this repo is "best effort" and per-config support requests will be closed, and that if you have a problem you should send a PR. That was removed in #910 , maybe we should revisit it.

Agreed a bit, I removed it because I saw many comments along the lines of "the built-in client/lspconfig" is not stable, but we could add some sort of disclaimer that while the client is stable, the configurations are maintained by users (in many cases me as well).

> We should add a generic project concept neovim/neovim#8610 and "root finder" to core, drawing from prior art like https://github.com/airblade/vim-rooter and https://github.com/tpope/vim-projectionist . It is generally useful for things beyond LSP.

100%. I wanted to pilot it here and move it to core once it has stabilized similar to how I migrated some of the handler overrides/lspconfig functionality to core. It could live in a separate repo as well. LspConfig has these things, but they are only semi-exposed to the user, and the implementation could be much better.

> 100 , agreed that we should continue improve :help lsp and vim.lsp so that simple things are easy (simple use-cases where the user knows (1) the filetype , (2) how to find the server, (3) the project root). :help lsp should have a small (half-page) of code that can be copy-pasted into init.lua.

Yes, it's really as easy as:

```lua
LaunchPyright = function()
  local client_id = vim.lsp.start_client({
      cmd = {"pyright-langserver", "--stdio"};
      settings = {
        python = {
          analysis = {
            autoSearchPaths = true;
            useLibraryCodeForTypes = true;
          };
        };
      };
      on_init = function(client, _)
        client.notify('workspace/didChangeConfiguration', {
          settings = client.config.settings;
        })
      end
    })
  vim.lsp.buf_attach_client(0, client_id)
end

vim.cmd([[
  command! -range LaunchPyright  execute 'lua LaunchPyright()'
]])
```

In my ideal world (an lspconfig 2.0 future), it would be as easy as:
```lua
LaunchPyright = function()
  local client_id = vim.lsp.start_client(require('lspconfig.pyright.config'))
  vim.lsp.buf_attach_client(0, client_id)
end

vim.cmd([[
  command! -range LaunchPyright  execute 'lua LaunchPyright()'
]])
```

People seem to think they *need* lspconfig to use the client, although the above is cumbersome (especially managing attaching buffers to language servers)

**Comment by justinmk** [comment]
> I wanted to pilot it here and move it to core once it has stabilized similar to how I migrated some of the handler overrides/lspconfig functionality to core.

ah, sure.



> above example is cumbersome, especially managing attaching buffers to language servers.

what do you mean? is the example missing some "management" aspect?

**Comment by mjlbach** [comment]
> what do you mean? is the example missing some "management" aspect?

Yes, right now this will launch the language server and *only* attach the current buffer (0 attaches current buffer) in `vim.lsp.buf_attach_client(0, client_id)`. In lspconfig, we have an auto command that invokes this for every current buffer where the file path of the buffer falls under the root directory as defined in lspconfig (which is also sent as the root directory of the server). With the above snippet, the user would have to call `vim.lsp.buf_attach_client(0, client_id)` on each new buffer.
